"""adding tag 4

Revision ID: 0052f3d8b9ba
Revises: 316ad74d0b9b
Create Date: 2023-03-20 16:52:05.790939

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0052f3d8b9ba'
down_revision = '316ad74d0b9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
