"""adding tag 4

Revision ID: 029e59bbe6c3
Revises: 1803be01ac3b
Create Date: 2023-03-20 16:54:33.722451

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '029e59bbe6c3'
down_revision = '1803be01ac3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
