"""shared notes

Revision ID: 0712b8e1581f
Revises: 3b0bc15b1a67
Create Date: 2022-12-28 15:49:42.150638

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0712b8e1581f'
down_revision = '3b0bc15b1a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
