"""user

Revision ID: 0902b90e5b7f
Revises: 13a7db048542
Create Date: 2022-11-27 20:41:01.238898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0902b90e5b7f'
down_revision = '13a7db048542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
