"""back_populates

Revision ID: 0b56860e6c6f
Revises: daf70b91899b
Create Date: 2022-11-30 17:23:15.696608

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0b56860e6c6f'
down_revision = 'daf70b91899b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
