"""shared notes

Revision ID: 0f0117ca7294
Revises: d841a225cc70
Create Date: 2022-12-21 17:17:19.813988

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0f0117ca7294'
down_revision = 'd841a225cc70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
