"""adding tag

Revision ID: 0fb3107786bf
Revises: 1727084f57a3
Create Date: 2023-03-20 16:12:07.067084

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0fb3107786bf'
down_revision = '1727084f57a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
