"""changing tag

Revision ID: 12f104ccf40b
Revises: 62555d70d30c
Create Date: 2023-03-22 00:10:19.799905

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '12f104ccf40b'
down_revision = '62555d70d30c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'tags')
    # ### end Alembic commands ###
