"""adding tag 2

Revision ID: 17b31a1febbb
Revises: e59bfefc4e29
Create Date: 2023-03-20 16:44:46.681674

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '17b31a1febbb'
down_revision = 'e59bfefc4e29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
