"""adding tag 4

Revision ID: 1803be01ac3b
Revises: c4a4b366a950
Create Date: 2023-03-20 16:54:10.475176

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1803be01ac3b'
down_revision = 'c4a4b366a950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
