"""shared notes

Revision ID: 1f3b98a6a297
Revises: a5572b1a9f52
Create Date: 2022-12-21 18:51:14.376010

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1f3b98a6a297'
down_revision = 'a5572b1a9f52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
