"""adding tag

Revision ID: 24ba355c649b
Revises: 7f683ddeefa7
Create Date: 2023-03-20 16:40:08.571527

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '24ba355c649b'
down_revision = '7f683ddeefa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
