"""adding tag 4

Revision ID: 316ad74d0b9b
Revises: 4154e4b4be65
Create Date: 2023-03-20 16:50:42.861907

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '316ad74d0b9b'
down_revision = '4154e4b4be65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
