"""shared notes

Revision ID: 3b0bc15b1a67
Revises: fe213d70b0d3
Create Date: 2022-12-28 15:42:47.884921

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3b0bc15b1a67'
down_revision = 'fe213d70b0d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share', 'with_childs')
    op.drop_column('share', 'public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('share', sa.Column('with_childs', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
