"""adding tag 3

Revision ID: 4154e4b4be65
Revises: f66814d97697
Create Date: 2023-03-20 16:48:46.916679

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4154e4b4be65'
down_revision = 'f66814d97697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
