"""Changing models

Revision ID: 4254a0c5db49
Revises: b1048aa596a5
Create Date: 2022-11-29 18:17:07.479936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4254a0c5db49'
down_revision = 'b1048aa596a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
