"""adding tag 4

Revision ID: 4579eeef5c3c
Revises: 0052f3d8b9ba
Create Date: 2023-03-20 16:52:24.617345

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4579eeef5c3c'
down_revision = '0052f3d8b9ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
