"""adding tag

Revision ID: 4c05ccfc8d8f
Revises: 0fb3107786bf
Create Date: 2023-03-20 16:32:50.011731

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4c05ccfc8d8f'
down_revision = '0fb3107786bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
