"""shared notes

Revision ID: 57dac8388973
Revises: 9eeefc54e200
Create Date: 2022-12-28 16:03:57.718452

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '57dac8388973'
down_revision = '9eeefc54e200'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
