"""shared notes

Revision ID: 59824a2832a4
Revises: c2038df0243e
Create Date: 2022-12-20 22:38:41.480889

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '59824a2832a4'
down_revision = 'c2038df0243e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
