"""adding tag 4

Revision ID: 62555d70d30c
Revises: 029e59bbe6c3
Create Date: 2023-03-20 17:13:40.616010

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '62555d70d30c'
down_revision = '029e59bbe6c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
