"""optional content

Revision ID: 715eb1b61fa0
Revises: 5292c522d05d
Create Date: 2022-12-19 21:43:46.339166

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '715eb1b61fa0'
down_revision = '5292c522d05d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
