"""shared notes

Revision ID: 786c5e7abb37
Revises: 4f73ad516b80
Create Date: 2022-12-21 18:59:12.646294

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '786c5e7abb37'
down_revision = '4f73ad516b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
