"""adding tag

Revision ID: 7f683ddeefa7
Revises: 4c05ccfc8d8f
Create Date: 2023-03-20 16:39:02.746664

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7f683ddeefa7'
down_revision = '4c05ccfc8d8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
