"""shared notes

Revision ID: 9eeefc54e200
Revises: 0712b8e1581f
Create Date: 2022-12-28 15:54:35.680812

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9eeefc54e200'
down_revision = '0712b8e1581f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
