"""self

Revision ID: 9fd1dc770122
Revises: 0b56860e6c6f
Create Date: 2022-12-06 22:56:20.987395

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9fd1dc770122'
down_revision = '0b56860e6c6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'path')
    # ### end Alembic commands ###
