"""New Migration

Revision ID: a253019e2ae4
Revises: a55ba379778f
Create Date: 2022-12-30 23:50:22.828523

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a253019e2ae4'
down_revision = 'a55ba379778f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('can_view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share', 'can_view')
    # ### end Alembic commands ###
