"""shared notes

Revision ID: a5572b1a9f52
Revises: 8d2471055499
Create Date: 2022-12-21 18:31:29.459878

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a5572b1a9f52'
down_revision = '8d2471055499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
