"""Changing models

Revision ID: aa162e21bca7
Revises: f35b4a4cf8d7
Create Date: 2022-11-29 18:23:58.915319

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'aa162e21bca7'
down_revision = 'f35b4a4cf8d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
