"""Changing models

Revision ID: b1048aa596a5
Revises: b8dfd738d411
Create Date: 2022-11-29 18:06:10.497675

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b1048aa596a5'
down_revision = 'b8dfd738d411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notebook', 'user', ['owner_id'], ['id'])
    op.add_column('user', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_updated')
    op.drop_column('user', 'time_created')
    op.drop_constraint(None, 'notebook', type_='foreignkey')
    op.drop_column('notebook', 'owner_id')
    # ### end Alembic commands ###
