"""shared notes

Revision ID: b139d3022b6f
Revises: e370dcd44d9f
Create Date: 2022-12-20 22:42:14.787820

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b139d3022b6f'
down_revision = 'e370dcd44d9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
