"""user

Revision ID: b8dfd738d411
Revises: 2d9a396d1d1f
Create Date: 2022-11-28 18:28:10.172045

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b8dfd738d411'
down_revision = '2d9a396d1d1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
