"""shared notes

Revision ID: be7eeae3dc89
Revises: b139d3022b6f
Create Date: 2022-12-20 22:43:20.341746

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'be7eeae3dc89'
down_revision = 'b139d3022b6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('share_shared_by_fkey', 'share', type_='foreignkey')
    op.drop_column('share', 'shared_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('shared_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('share_shared_by_fkey', 'share', 'user', ['shared_by'], ['id'])
    # ### end Alembic commands ###
