"""adding tag 4

Revision ID: c4a4b366a950
Revises: 4579eeef5c3c
Create Date: 2023-03-20 16:53:56.526619

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c4a4b366a950'
down_revision = '4579eeef5c3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
