"""shared notes

Revision ID: d841a225cc70
Revises: be7eeae3dc89
Create Date: 2022-12-20 22:44:16.479412

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd841a225cc70'
down_revision = 'be7eeae3dc89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
