"""Changing models

Revision ID: daf70b91899b
Revises: aa162e21bca7
Create Date: 2022-11-29 18:33:14.103025

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'daf70b91899b'
down_revision = 'aa162e21bca7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
