"""shared notes

Revision ID: e370dcd44d9f
Revises: 59824a2832a4
Create Date: 2022-12-20 22:40:41.995283

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e370dcd44d9f'
down_revision = '59824a2832a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('note_id', sa.Integer(), nullable=True))
    op.add_column('share', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'share', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'share', 'note', ['note_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share', type_='foreignkey')
    op.drop_constraint(None, 'share', type_='foreignkey')
    op.drop_column('share', 'user_id')
    op.drop_column('share', 'note_id')
    # ### end Alembic commands ###
