"""adding tag

Revision ID: e59bfefc4e29
Revises: 24ba355c649b
Create Date: 2023-03-20 16:42:15.346521

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e59bfefc4e29'
down_revision = '24ba355c649b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
