"""Changing models

Revision ID: f35b4a4cf8d7
Revises: 4254a0c5db49
Create Date: 2022-11-29 18:23:30.732617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35b4a4cf8d7'
down_revision = '4254a0c5db49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
