"""adding tag 3

Revision ID: f66814d97697
Revises: 17b31a1febbb
Create Date: 2023-03-20 16:46:12.269204

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f66814d97697'
down_revision = '17b31a1febbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
