"""shared notes

Revision ID: fe213d70b0d3
Revises: 786c5e7abb37
Create Date: 2022-12-21 19:25:37.369960

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fe213d70b0d3'
down_revision = '786c5e7abb37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('with_childs', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share', 'with_childs')
    # ### end Alembic commands ###
